version: '3.8'


services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  database:
    image: 'postgres:16'
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=1122'


